import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Masthead from '../components/masthead'
import AboutMe from '../components/aboutme'
import Skills from '../components/skills'
import Works from '../components/works'
import FollowMe from '../components/followme'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Masthead />
      <AboutMe></AboutMe>
      <Skills></Skills>
      <Works></Works>
      <FollowMe></FollowMe>
      <div className="md:pt-20 justify-center flex bg-white">
            <Image src ="/assets/ao.png" width={128 / 2} height={114 / 4} alt="logo"></Image>
      </div>
    </div>
  )
}

export default Home
